"""
Synthetic Data Generator — creates realistic batches of simulated cases.

ALL DATA GENERATED BY THIS MODULE IS SIMULATED.
Never imply it is real Razorpay data.

Generates:
- ~30 failed payment cases with realistic failure-code distributions
- ~50 B2B receivable cases with varied histories, disputes, and relationship profiles

Key design choices:
- Relationship tiers are computed in a SECOND PASS after the full batch is
  generated, because value percentile (V) requires all amounts to exist first.
  (Confirmed requirement — computing per-case during generation would silently
  break every tier assignment.)
- 2–3 failed payment cases below ₹500 for cost-threshold testing
- 2–3 B2B cases below ₹5,000 for B2B cost-threshold testing
- ~5 B2B cases with dispute_flag=True
- ~3 B2B cases with broken promise-to-pay
- 2 cases with conflicting_signals for Stress Test scenario 8
- ~3 fraud-flagged payment cases
- A handful of cases at attempt cap for boundary testing

Output: JSON files in data/ directory with "data_type": "SIMULATED" metadata.
"""

from __future__ import annotations

import json
import os
import random
import uuid
from datetime import datetime, timedelta
from typing import Any

from core import config
from core.relationship import compute_tiers_for_batch
from core.schemas import (
    B2BReceivableCase,
    ConflictingSignal,
    CustomerHistory,
    FailedPaymentCase,
    FailureCode,
    PromiseToPay,
    case_to_dict,
)

# Reproducible randomness for consistent synthetic data
SEED = 42
_rng = random.Random(SEED)

# Output directory
DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)))


def _uuid() -> str:
    """Generate a deterministic-looking UUID from our seeded RNG."""
    return str(uuid.UUID(int=_rng.getrandbits(128), version=4))


def _random_datetime(start: datetime, end: datetime) -> datetime:
    """Random datetime between start and end."""
    delta = end - start
    random_seconds = _rng.randint(0, int(delta.total_seconds()))
    return start + timedelta(seconds=random_seconds)


# ---------------------------------------------------------------------------
# Failed Payment Case Generator
# ---------------------------------------------------------------------------

def _generate_failed_payments(count: int = 30) -> list[FailedPaymentCase]:
    """Generate ~30 failed payment cases with realistic distributions."""
    cases: list[FailedPaymentCase] = []
    ref_now = config.SIMULATED_CURRENT_TIME

    # Failure code distribution: ~35% insufficient, ~25% timeout, ~20% auth,
    # ~10% gateway, ~10% fraud
    failure_weights = [
        (FailureCode.INSUFFICIENT_FUNDS, 35),
        (FailureCode.BANK_TIMEOUT, 25),
        (FailureCode.AUTH_FAILURE, 20),
        (FailureCode.GATEWAY_ERROR, 10),
        (FailureCode.FRAUD_REJECTION, 10),
    ]
    failure_codes = []
    for code, weight in failure_weights:
        failure_codes.extend([code] * weight)

    # Amount ranges (skewed toward smaller)
    def _random_amount(low_value: bool = False) -> float:
        if low_value:
            return round(_rng.uniform(50, 450), 2)   # Below ₹500 threshold
        r = _rng.random()
        if r < 0.50:
            return round(_rng.uniform(500, 5000), 2)       # Small
        elif r < 0.80:
            return round(_rng.uniform(5000, 25000), 2)     # Medium
        elif r < 0.95:
            return round(_rng.uniform(25000, 50000), 2)    # Large
        else:
            return round(_rng.uniform(50000, 200000), 2)   # Very large

    # Generate 30 customer IDs (some customers have multiple failures)
    customer_pool_size = 22
    customer_ids = [f"CUST-{_uuid()[:8]}" for _ in range(customer_pool_size)]

    for i in range(count):
        # 2–3 below cost threshold
        low_value = i < 3
        amount = _random_amount(low_value=low_value)

        # Failure code
        failure_code = _rng.choice(failure_codes)

        # Fraud flag: always True for FRAUD_REJECTION, occasionally for others
        fraud_flag = failure_code == FailureCode.FRAUD_REJECTION
        if not fraud_flag and _rng.random() < 0.02:
            fraud_flag = True

        # Attempt count: mostly 1, some higher, a few at boundary
        if i < 2:
            attempt_count = 5  # At cap — for boundary testing
        elif _rng.random() < 0.3:
            attempt_count = _rng.randint(2, 4)
        else:
            attempt_count = 1

        # Customer history
        customer_id = _rng.choice(customer_ids)
        has_history = _rng.random() > 0.2  # 80% have history
        if has_history:
            reliability = round(_rng.uniform(0.2, 1.0), 2)
            transactions = _rng.randint(1, 80)
            total_amount = round(_rng.uniform(1000, 500000), 2)
        else:
            reliability = 0.5  # cold-start default
            transactions = 0
            total_amount = 0.0

        history = CustomerHistory(
            reliability_ratio=reliability,
            total_transactions=transactions,
            total_amount=total_amount,
            has_history=has_history,
        )

        # Timestamp: within the last 7 days from simulation anchor
        timestamp = _random_datetime(ref_now - timedelta(days=7), ref_now)

        # Conflicting signals: add to 1 payment case (scenario 8)
        conflicting_signals = []
        if i == 15:  # One specific case gets conflicting signals
            conflicting_signals = [
                ConflictingSignal(
                    source_a="risk_score_engine",
                    signal_a="safe_to_retry",
                    source_b="customer_support_ticket",
                    signal_b="customer_requested_stop_contact",
                    description="Risk engine marks this as safe to retry, but an "
                                "open support ticket shows the customer explicitly "
                                "asked to stop contact.",
                )
            ]

        case = FailedPaymentCase(
            case_id=f"PAY-{_uuid()[:12]}",
            amount=amount,
            failure_code=failure_code,
            timestamp=timestamp,
            attempt_count=attempt_count,
            customer_id=customer_id,
            customer_history=history,
            fraud_flag=fraud_flag,
            conflicting_signals=conflicting_signals,
            created_at=timestamp,
        )
        cases.append(case)

    return cases


# ---------------------------------------------------------------------------
# B2B Receivable Case Generator
# ---------------------------------------------------------------------------

def _generate_b2b_receivables(count: int = 50) -> list[B2BReceivableCase]:
    """Generate ~50 B2B receivable cases with realistic distributions."""
    cases: list[B2BReceivableCase] = []
    ref_now = config.SIMULATED_CURRENT_TIME

    # Debtor pool (fewer debtors than cases — some debtors have multiple invoices)
    debtor_pool_size = 30
    debtor_ids = [f"DBT-{_uuid()[:8]}" for _ in range(debtor_pool_size)]

    # Amount ranges: ₹10,000–₹50,00,000 skewed toward mid-range
    # PLUS 2–3 below ₹5,000 for B2B cost-threshold testing
    def _random_b2b_amount(low_value: bool = False) -> float:
        if low_value:
            return round(_rng.uniform(1000, 4500), 2)  # Below ₹5,000 threshold
        r = _rng.random()
        if r < 0.40:
            return round(_rng.uniform(10000, 100000), 2)       # Small B2B
        elif r < 0.75:
            return round(_rng.uniform(100000, 500000), 2)      # Mid-range
        elif r < 0.92:
            return round(_rng.uniform(500000, 2000000), 2)     # Large
        else:
            return round(_rng.uniform(2000000, 5000000), 2)    # Very large

    for i in range(count):
        # 2–3 below B2B cost threshold
        low_value = i < 3
        amount = _random_b2b_amount(low_value=low_value)

        debtor_id = _rng.choice(debtor_ids)

        # Days overdue: 1–90, realistic distribution
        days_overdue = max(1, int(_rng.expovariate(1 / 25)))  # mean ~25 days
        days_overdue = min(days_overdue, 90)
        due_date = ref_now - timedelta(days=days_overdue)
        invoice_date = due_date - timedelta(days=_rng.randint(15, 45))

        # Debtor history
        has_history = _rng.random() > 0.15  # 85% have history
        if has_history:
            reliability = round(_rng.uniform(0.1, 1.0), 2)
            transactions = _rng.randint(1, 100)
            total_amount = round(_rng.uniform(50000, 5000000), 2)
        else:
            reliability = 0.5
            transactions = 0
            total_amount = 0.0

        history = CustomerHistory(
            reliability_ratio=reliability,
            total_transactions=transactions,
            total_amount=total_amount,
            has_history=has_history,
        )

        # Dispute flag: ~10% of cases
        dispute_flag = i < 5  # First 5 cases are disputed (ensures exactly 5)

        # Fraud flag: ~4% of B2B cases
        fraud_flag = i in (7, 8)  # 2 fraud-flagged cases

        # Attempt/contact count
        if _rng.random() < 0.2:
            attempt_count = _rng.randint(3, 4)  # At or near cap
            contact_count = _rng.randint(2, 4)
        else:
            attempt_count = _rng.randint(0, 2)
            contact_count = _rng.randint(0, 2)

        # Promise-to-pay: ~15% have one, ~3 of those are broken
        promise = None
        if 20 <= i < 28:  # 8 cases get promises
            promise_date = ref_now + timedelta(days=_rng.randint(-5, 15))
            kept = None
            if i < 23:
                # 3 broken promises (promise date in the past, not kept)
                promise_date = ref_now - timedelta(days=_rng.randint(1, 10))
                kept = False
            elif promise_date < ref_now:
                kept = True  # Past due and kept
            promise = PromiseToPay(
                promised_date=promise_date,
                promised_amount=amount,
                kept=kept,
            )

        # Conflicting signals: 1 B2B case (scenario 8)
        conflicting_signals = []
        if i == 35:
            conflicting_signals = [
                ConflictingSignal(
                    source_a="payment_history_analysis",
                    signal_a="debtor_likely_to_pay_soon",
                    source_b="credit_report_update",
                    signal_b="debtor_credit_rating_downgraded",
                    description="Payment history suggests the debtor is likely to "
                                "pay soon, but a recent credit report shows their "
                                "rating was downgraded — conflicting recovery outlook.",
                )
            ]

        case = B2BReceivableCase(
            case_id=f"B2B-{_uuid()[:12]}",
            invoice_id=f"INV-{_uuid()[:10]}",
            amount=amount,
            invoice_date=invoice_date,
            due_date=due_date,
            debtor_id=debtor_id,
            debtor_history=history,
            attempt_count=attempt_count,
            contact_count=contact_count,
            dispute_flag=dispute_flag,
            fraud_flag=fraud_flag,
            promise_to_pay=promise,
            conflicting_signals=conflicting_signals,
            created_at=invoice_date,
        )
        cases.append(case)

    return cases


# ---------------------------------------------------------------------------
# Batch Generation (with second-pass tier computation)
# ---------------------------------------------------------------------------

def generate_full_batch() -> dict[str, list]:
    """Generate the full synthetic data batch.

    IMPORTANT: Relationship tiers are computed in a SECOND PASS after all
    cases exist, because value percentile (V) requires the full portfolio
    of amounts. Computing per-case during generation would quietly break
    every tier assignment by evaluating percentiles against a partial batch.
    """
    print("Generating synthetic data batch (ALL DATA IS SIMULATED)...")

    # Step 1: Generate raw cases (no tiers yet)
    payment_cases = _generate_failed_payments(30)
    b2b_cases = _generate_b2b_receivables(50)

    # Step 2: Compute relationship tiers in a SECOND PASS
    # Payment and B2B tiers are computed within their own scenario pools,
    # since value percentile is only meaningful within the same case type.
    print(f"  Computing relationship tiers for {len(payment_cases)} payment cases...")
    payment_results = compute_tiers_for_batch(payment_cases)

    print(f"  Computing relationship tiers for {len(b2b_cases)} B2B cases...")
    b2b_results = compute_tiers_for_batch(b2b_cases)

    # Step 3: Report distribution
    _report_distribution("Failed Payments", payment_cases, payment_results)
    _report_distribution("B2B Receivables", b2b_cases, b2b_results)

    return {
        "failed_payments": payment_cases,
        "b2b_receivables": b2b_cases,
    }


def _report_distribution(label: str, cases: list, results: list) -> None:
    """Print a summary of the generated batch for verification."""
    print(f"\n  --- {label} ({len(cases)} cases) ---")

    # Amount range
    amounts = [c.amount for c in cases]
    print(f"  Amount range: ₹{min(amounts):,.2f} – ₹{max(amounts):,.2f}")

    # Tier distribution
    tiers = {}
    for case, _, _ in results:
        tier = case.relationship_tier.value if case.relationship_tier else "NONE"
        tiers[tier] = tiers.get(tier, 0) + 1
    print(f"  Tier distribution: {tiers}")

    # Special cases
    if hasattr(cases[0], "failure_code"):
        fraud_count = sum(1 for c in cases if c.fraud_flag)
        low_value_count = sum(1 for c in cases if c.amount < 500)
        at_cap = sum(1 for c in cases if c.attempt_count >= 5)
        conflict_count = sum(1 for c in cases if c.conflicting_signals)
        print(f"  Fraud-flagged: {fraud_count}")
        print(f"  Below ₹500 threshold: {low_value_count}")
        print(f"  At attempt cap (5): {at_cap}")
        print(f"  With conflicting signals: {conflict_count}")
    else:
        dispute_count = sum(1 for c in cases if c.dispute_flag)
        fraud_count = sum(1 for c in cases if c.fraud_flag)
        low_value_count = sum(1 for c in cases if c.amount < 5000)
        promise_count = sum(1 for c in cases if c.promise_to_pay)
        broken = sum(1 for c in cases if c.promise_to_pay and c.promise_to_pay.kept is False)
        conflict_count = sum(1 for c in cases if c.conflicting_signals)
        print(f"  Disputed: {dispute_count}")
        print(f"  Fraud-flagged: {fraud_count}")
        print(f"  Below ₹5,000 threshold: {low_value_count}")
        print(f"  With promise-to-pay: {promise_count} (broken: {broken})")
        print(f"  With conflicting signals: {conflict_count}")


def save_batch(batch: dict[str, list], output_dir: str | None = None) -> dict[str, str]:
    """Save the generated batch to JSON files.

    Returns a dict of {scenario_name: file_path}.
    """
    out_dir = output_dir or DATA_DIR
    os.makedirs(out_dir, exist_ok=True)
    paths = {}

    for scenario_name, cases in batch.items():
        file_path = os.path.join(out_dir, f"{scenario_name}.json")
        data = {
            "data_type": "SIMULATED",
            "generated_at": datetime.now().isoformat(),
            "description": (
                "Synthetic data for the AI Revenue Recovery Agent. "
                "ALL DATA IS SIMULATED — never imply real Razorpay data."
            ),
            "count": len(cases),
            "cases": [case_to_dict(c) for c in cases],
        }
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)
        print(f"  Saved {len(cases)} cases to {file_path}")
        paths[scenario_name] = file_path

    return paths


def generate_all(output_dir: str | None = None) -> dict[str, str]:
    """Generate and save all synthetic datasets to disk (anchored to SIMULATED_CURRENT_TIME)."""
    batch = generate_full_batch()
    return save_batch(batch, output_dir=output_dir)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    paths = generate_all()
    print(f"\nDone. Files saved: {list(paths.values())}")
